apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: database
  description: This is a demo service
  tags:
    - java
    - spring
  annotations:
    sonarqube.org/project-key: testorg1923/TestOrg1923_repo
    backstage.io/kubernetes-id: database
    github.com/project-slug: TestOrg1923/repo
    goharbor.io/repository-slug:: stefanprodan-podinfo-clone/podinfo
spec:
  type: service
  lifecycle: production
  owner: team
  system: Multifornecedor
  dependsOn:
    - resource:CosmosDB
    
