apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: database
  description: This is a demo service
  tags:
    - java
    - spring
  annotations:
    sonarqube.org/project-key: testorg1923/TestOrg1923_database
    backstage.io/kubernetes-id: database
    github.com/project-slug: TestOrg1923/database
    goharbor.io/repository-slug: inspection-demo/regression-issue-74839
spec:
  type: service
  lifecycle: production
  owner: team
  system: Multifornecedor
  dependsOn:
    - resource:CosmosDB
    
