apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service
  description: This is a demo service
  tags:
    - nodejs
    - backend
  annotations:
    sonarqube.org/project-key: sqp_816f665d926716ffdabc971b75d36320e7f81e00
spec:
  type: service
  lifecycle: production
  owner: team
