apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service
  description: This is a demo service
  tags:
    - nodejs
    - backend
  annotations:
    sonarqube.org/project-key: TestOrg1923_repo
spec:
  type: service
  lifecycle: production
  owner: team
