apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service
  description: This is a demo service
  tags:
    - nodejs
    - backend
  annotations:
    http://localhost:5000/project-key: TestOrg1923_repo_AYLt_lGppl-OSC-IurYj
    jira/project-key: SSP
spec:
  type: service
  lifecycle: production
  owner: team
